### PR TITLE
Explicit methods for mandatory bindings

### PR DESCRIPTION
**Pull request by planger**
This change sketches an alternative approach to explicitly force mandatory bindings in diagram modules.

https://github.com/eclipse-glsp/glsp/issues/620

### CODE REVIEW

**Comment by tortmayr** [comment]
@planger  I have pushed a new proposal using `BindingTargets` (as discussed in  in https://github.com/eclipse-glsp/glsp/issues/620)
WDYT?

**Comment by planger** [comment]
Oh, nice! Yeah that looks great actually! Thanks a lot!

**Comment by tortmayr** [comment]
Thanks for the feedback. So should we go ahead and introduce explicit method bindings for all diagram module bindings?
Then the Java and Node API would be more or less aligned.
Adopters can then  chose whether they want to rebind certain services by overwriting  the  corresponding method or if they wan to go the `standard` inversify route and implement and load a new module that provides the rebinds.

**Comment by planger** [comment]
Yes, I'd be in favor of that. But of course, as always it is a matter of time. If it fits nicely with preparing the getting-started examples, that'd be great. But I'd consider those to have higher prio.

Thanks!

**Pull request closed without merging**
